### ISSUE TITLE
 when I compile openwrt for Raspberry Pi, display an error

### ISSUE THREAD

**Issue by wzc0x0** [olivluca/mt7601-openwrt#1]
scripts/Makefile.build:257: recipe for target '/home/wzc0x0/bin/brcm2708/sdk/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2708/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../os/linux/rt_linux.o' failed
make[5]: **\* [/home/wzc0x0/bin/brcm2708/sdk/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2708/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux/../../os/linux/rt_linux.o] Error 1
Makefile:1381: recipe for target '_module_/home/wzc0x0/bin/brcm2708/sdk/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2708/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux' failed
make[4]: **\* [_module_/home/wzc0x0/bin/brcm2708/sdk/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2708/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/os/linux] Error 2
make[4]: Leaving directory '/home/wzc0x0/bin/brcm2708/sdk/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2708/linux-3.18.19'
Makefile:394: recipe for target 'LINUX' failed
make[3]: **\* [LINUX] Error 2
make[3]: Leaving directory '/home/wzc0x0/bin/brcm2708/sdk/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2708/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913'
Makefile:78: recipe for target '/home/wzc0x0/bin/brcm2708/sdk/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2708/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/.built' failed
make[2]: **\* [/home/wzc0x0/bin/brcm2708/sdk/build_dir/target-arm_arm1176jzf-s+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2708/DPO_MT7601U_LinuxSTA_3.0.0.4_20130913/.built] Error 2
make[2]: Leaving directory '/home/wzc0x0/bin/brcm2708/sdk/package/mt7601-openwrt'
package/Makefile:191: recipe for target 'package/mt7601-openwrt/compile' failed
make[1]: **\* [package/mt7601-openwrt/compile] Error 2
make[1]: Leaving directory '/home/wzc0x0/bin/brcm2708/sdk'
/home/wzc0x0/bin/brcm2708/sdk/include/toplevel.mk:174: recipe for target 'package/mt7601-openwrt/compile' failed
make: **\* [package/mt7601-openwrt/compile] Error 2

Can you help me deal with this problem? Thank you !

**Comment by olivluca** [comment]
Please look here:
https://github.com/openwrt/packages/issues/861
